
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
    volumes:
      - redis-v:/data
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
    ports:
      - '81:5050'
  web2:
    restart: on-failure
    build: ./web
    ports:
      - '82:5050'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
volumes:
  redis-v:
   name: redis-v

